[package]
name = "kreck"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = ["tray-icon", "image-ico", "image-png"] }
tauri-plugin-shell = "2.0.0-beta"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-positioner = { version = "2.0.0-beta", features = ["tray-icon"] }
rocket = { version = "0.5.0", features = ["secrets", "json"] }
tokio = { version = "1.17", features = ["full"] }
kenku_control = "0.2.3"
local-ip-address = "0.6.1"
